### ISSUE TITLE
Transient test failure on EL7

### ISSUE THREAD

**Issue by cottsay** [osrf/osrf_pycommon#23]
This has only come up once (so far), but I experienced a transient unit test failure while packaging `osrf_pycommon` for Fedora and EPEL[1].

The build log[2] indicates that the failing test is `test__execute_process_pty`:

```
nosetests -w tests
.................F..............
======================================================================
FAIL: test__execute_process_pty (tests.unit.test_process_utils.test_execute_process_pty.TestProcessUtilsExecuteNoPty)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/osrf_pycommon-0.1.2/tests/unit/test_process_utils/test_execute_process_pty.py", line 104, in test__execute_process_pty
    self.assertEqual(expected, result)
AssertionError: 'out 1\r\nerr 1\r\nout 2\r\n' != ''
----------------------------------------------------------------------
Ran 32 tests in 0.467s
FAILED (failures=1)
```

I re-ran the same build, and it passed the second time, so unfortunately I don't have a consistent repro. I'm hoping something jumps out for one of the developers, so we can avoid the build failures in the future. If not, I just wanted to make you were aware that the test had failed.

Thanks,

--scott

[1] http://koji.fedoraproject.org/koji/taskinfo?taskID=13941586
[2] https://kojipkgs.fedoraproject.org//work/tasks/1586/13941586/build.log

**Comment by clalancette** [comment]
Sorry we didn't get a chance to look at this earlier.  Looking at recent Koji builds, it seems like this isn't really a problem anymore (at least, the last ten builds don't seem to have seen this).  Do you think this is still a problem, or should we close this out for now?
