### ISSUE TITLE
Missing from yakkety and zesty repositories

### ISSUE THREAD

**Issue by ipa-mdl** [osrf/osrf_pycommon#35]
`python[3]-osrf-pycommon` is missing from [yakkety](http://packages.ros.org/ros-shadow-fixed/ubuntu/dists/yakkety/main/binary-amd64/Packages) and [zesty](http://packages.ros.org/ros-shadow-fixed/ubuntu/dists/zesty/main/binary-amd64/Packages]) repositores, at least for `amd64` and `armhf`, but `python[3]-catkin-tools` depends on it.

**Comment by wjwwood** [comment]
Thanks for pointing this out. I've added the additional suites in #36. I just need to flood the new debs into the repositories. I'll do that now and let you know when it should be working.

**Comment by ipa-mdl** [comment]
Thanks!
I will close it as soon as it reaches `ros-shadow-fixed` :)

**Comment by wjwwood** [comment]
Looks like they are there now.

**Comment by ipa-mdl** [comment]
travis is happy now :tada:
