### ISSUE TITLE
DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8

### ISSUE THREAD

**Issue by dirk-thomas** [osrf/osrf_pycommon#61]
https://github.com/osrf/osrf_pycommon/blob/e3ceab6867f1da1e86f30c21ac578b0dbeb8831d/osrf_pycommon/process_utils/async_execute_process_asyncio/impl.py#L54

**Comment by dirk-thomas** [comment]
Instead of creating separate tickets for each deprecation warning I will add more here:

* `osrf_pycommon/cli_utils/verb_pattern.py:44`:

  > DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()

* `osrf_pycommon/tests/unit/test_cli_utils/test_verb_pattern.py:69`:

  > DeprecationWarning: Please use assertRaisesRegex instead.

**Comment by zmk5** [comment]
According to the python [docs](https://docs.python.org/3/library/asyncio-task.html), `@asyncio.coroutine` should be replaced with `async def`. After trying this, however, I get errors that complain about the use of `yield` within an async definition used here:

```
        # Start the subprocess
        if shell is True:
            transport, protocol = yield from loop.subprocess_shell(
                protocol_factory, " ".join(cmd), cwd=cwd, env=env,
                stdout=stdout_slave, stderr=stderr_slave, close_fds=False)
        else:
            transport, protocol = yield from loop.subprocess_exec(
                protocol_factory, *cmd, cwd=cwd, env=env,
                stdout=stdout_slave, stderr=stderr_slave, close_fds=False)
```

**Comment by zmk5** [comment]
Additionally, I found out that >python3.6 supports [asynchronous generators](https://stackoverflow.com/questions/37549846/how-to-use-yield-inside-async-function), but not below. Fixing the first deprecation could have CI routines that fail to build for anything lower than python3.7.

**Comment by clalancette** [comment]
> Additionally, I found out that >python3.6 supports [asynchronous generators](https://stackoverflow.com/questions/37549846/how-to-use-yield-inside-async-function), but not below. Fixing the first deprecation could have CI routines that fail to build for anything lower than python3.7.

I think we still want to maintain compatibility with at least Python 3.6 (Ubuntu Bionic).  So that doesn't seem to be an option right now.

**Comment by zmk5** [comment]
That's what I thought, so the fix for the first deprecation will need to be a bit more creative haha.

**Comment by zmk5** [comment]
@ivanpauno I believe these are the issues you still found lingering with the `launch` bug. I'm still trying to figure out what do with the `asynchronous.coroutine`.

**Comment by jacobperron** [comment]
I think this was resolved in https://github.com/osrf/osrf_pycommon/pull/64
