### ISSUE TITLE
Remove `import mock` in test_terminal_utils.py

### ISSUE THREAD

**Issue by clalancette** [osrf/osrf_pycommon#73]
Based on the comment in https://github.com/ros2/ros2_documentation/pull/1452#discussion_r622511855 , we should probably replace the `import mock` at https://github.com/osrf/osrf_pycommon/blob/e891e29d8319c0b111bd9653e20e1f21e042ac25/tests/unit/test_terminal_utils.py#L1 with `from unittest import mock`, which will allow us to get rid of one pip dependency.  That is currently the only thing that relies on mock in the ROS 2 codebase.

**Comment by clalancette** [comment]
When we do fix this, we should update the documentation at https://github.com/ros2/ros2_documentation to get rid of the dependency.

**Comment by cottsay** [comment]
+1 from me. The `mock` package is [deprecated altogether in Fedora 34](https://fedoraproject.org/wiki/Changes/DeprecatePythonMock).
